[debug]

  [debug.quit]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "escape"

  [debug.console]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "f9"

  [debug.frame_rate_meter]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "f10"

  [debug.pdb]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "f11"

  [debug.pstats]
  _type = "trigger"
  _device_order = ["keyboard"]
  keyboard = "f12"

[character_movement]

  [character_movement.direction]
  _type = "axis2d"
  _device_order = ["gamepad", "flight_stick", "spatial_mouse", "keyboard"]
  gamepad = "left_x:exp=2,left_y:exp=2"
  flight_stick = "roll,pitch:flip"
  spatial_mouse = "x:scale=3,y:scale=3"
  keyboard = "a,d,s,w"

  [character_movement.rotation]
  _type = "axis2d"
  _device_order = ["gamepad", "flight_stick", "spatial_mouse", "keyboard"]
  gamepad = "right_x:exp=2,right_y:exp=2"
  flight_stick = "yaw:flip,pitch"
  spatial_mouse = "yaw:flip:scale=2,pitch"
  keyboard = "arrow_left,arrow_right,arrow_down,arrow_up"

[weapons]

  [weapons.primary]
  _type = "button"
  _device_order = ["keyboard"]
  keyboard = "space"

#  [weapons.secondary]
#  _type = "button"
#  _device_order = ["keyboard"]
#  keyboard = "space"

[camera_movement]

  [camera_movement.rotation]
  _type = "axis2d"
  _device_order = ["keyboard"]
  keyboard = "mouse_x_delta,mouse_y_delta"

  [camera_movement.zoom]
  _type = "axis"
  _device_order = ["keyboard"]
  keyboard = "u,o"
# 
# [clock_control]
# 
#   [clock_control.time_zoom]
#   _type = "axis"
#   _device_order = ["keyboard"]
#   keyboard = "-,+"
